#!/bin/bash -ex

#https://github.com/foodcoops/foodsoft/archive/refs/heads/master.zip download from master 

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

dlfs() {
    SRC=/usr/local/src
    dl https://github.com/foodcoops/foodsoft/archive/refs/heads/master.tar.gz $SRC
}

# download standard foodsoft
dlfs foodcoops/foodsoft       master        standard

